SplitMethods return Seq instead of Array
This is to avoid reflection error on Arrays now that Grid is parametric:

java.lang.ClassCastException: [Lgeotrellis.raster.Tile; cannot be cast to [Lgeotrellis.raster.Grid;
	at geotrellis.raster.package$withTileMethods.split(package.scala:56)
	at geotrellis.raster.split.SplitMethods$class.split(SplitMethods.scala:34)
	at geotrellis.raster.package$withTileMethods.split(package.scala:56)